# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 880)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setMinimumSize(QtCore.QSize(500, 0))
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.indexTitle = QtWidgets.QLabel(self.mainFrame)
        self.indexTitle.setObjectName("indexTitle")
        self.verticalLayout.addWidget(self.indexTitle)
        self.indexChartWidget = QtWidgets.QWidget(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indexChartWidget.sizePolicy().hasHeightForWidth())
        self.indexChartWidget.setSizePolicy(sizePolicy)
        self.indexChartWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.indexChartWidget.setMaximumSize(QtCore.QSize(16777215, 500))
        self.indexChartWidget.setSizeIncrement(QtCore.QSize(1, 0))
        self.indexChartWidget.setObjectName("indexChartWidget")
        self.verticalLayout.addWidget(self.indexChartWidget)
        self.contractTitle = QtWidgets.QLabel(self.mainFrame)
        self.contractTitle.setObjectName("contractTitle")
        self.verticalLayout.addWidget(self.contractTitle)
        self.contractChartWidget = QtWidgets.QWidget(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contractChartWidget.sizePolicy().hasHeightForWidth())
        self.contractChartWidget.setSizePolicy(sizePolicy)
        self.contractChartWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.contractChartWidget.setMaximumSize(QtCore.QSize(16777215, 500))
        self.contractChartWidget.setObjectName("contractChartWidget")
        self.verticalLayout.addWidget(self.contractChartWidget)
        self.contractChartWidget.raise_()
        self.contractTitle.raise_()
        self.indexTitle.raise_()
        self.indexChartWidget.raise_()
        self.horizontalLayout_2.addWidget(self.mainFrame)
        self.leftFrame = QtWidgets.QFrame(self.centralwidget)
        self.leftFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.leftFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contractTableTitle = QtWidgets.QLabel(self.leftFrame)
        self.contractTableTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contractTableTitle.setObjectName("contractTableTitle")
        self.verticalLayout_2.addWidget(self.contractTableTitle)
        self.contractTableView = QtWidgets.QWidget(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contractTableView.sizePolicy().hasHeightForWidth())
        self.contractTableView.setSizePolicy(sizePolicy)
        self.contractTableView.setMinimumSize(QtCore.QSize(0, 300))
        self.contractTableView.setMaximumSize(QtCore.QSize(500, 6666666))
        self.contractTableView.setObjectName("contractTableView")
        self.verticalLayout_2.addWidget(self.contractTableView)
        self.horizontalLayout_2.addWidget(self.leftFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.indexTitle.setText(_translate("MainWindow", "指数5分钟成交额"))
        self.contractTitle.setText(_translate("MainWindow", "概念板块5分钟成交额"))
        self.contractTableTitle.setText(_translate("MainWindow", "概念板块列表(东财)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
